# Docker composition orchestrating several containers to set up an inventory management application
# Lancement : docker compose -f hbntory_bo_docker-compose.yml up -d
# Arrêt     : docker compose -f hbntory_bo_docker-compose.yml down -v

name: ${COMPOSE_PROJECT_NAME}

services:
  # Holds the data pertaining quantities of products per store.
  stock-db-service:
    image: mariadb:latest
    container_name: hbntory-stock-db-service # Mandatory to avoid -n suffix for scaling
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # MariaDB_USER is automatically understood as "database admin" so all permissions granted.
      - MARIADB_DATABASE=${DB_HBNTORY_BASENAME}
      - MARIADB_USER=${DB_HBNTORY_USER_ID}
      - MARIADB_PASSWORD=${DB_HBNTORY_USER_PWD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - stock_db_data:/var/lib/mysql
      - ${PWD}/backoffice/init:/docker-entrypoint-initdb.d

  # Exposes detailed information for all products potentially available in company's stores
  products-api:
    build:
      context: https://github.com/hbtn-edu/hbntory-products-api.git#08497b1263a39aaddaf43a405722cbe93fc25b78
    image: hbntory_products_api:latest
    container_name: hbntory-products-api
    restart: unless-stopped
    ports:
      - "5000:5000"

  internal-api:
    build:
      context: ${PWD}/backoffice
      dockerfile: Dockerfile.internal_api
      # WARNING: using this would probably mess with COPY instructions inside
      #   because would be evaluated from "context" which would be one level too high.
      # context: ${PWD}
      # dockerfile: ./backoffice/Dockerfile.internal_api
    environment:
      - DB_HBNTORY_BASENAME=${DB_HBNTORY_BASENAME}
      - DB_HBNTORY_USER_PWD=${DB_HBNTORY_USER_PWD}
      - DB_HBNTORY_USER_ID=${DB_HBNTORY_USER_ID}
      - DB_HOST=stock-db-service
      - DB_PORT=3306
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    ports:
      - "8002:8002"
    depends_on:
      - stock-db-service

  backoffice:
    build:
      context: ${PWD}/backoffice
      dockerfile: Dockerfile.backoffice
    environment:
      # Using syntax providing default value as fallback,
      # :- means "use that if target is Undefined OR empty"
      - DB_HBNTORY_BASENAME=${DB_HBNTORY_BASENAME:-holberton_inventory}
      # No default because is essential info should always be provided
      - DB_HBNTORY_USER_PWD=${DB_HBNTORY_USER_PWD}
      - DB_HBNTORY_USER_ID=${DB_HBNTORY_USER_ID}
      - DB_HOST=stock-db-service
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_SECRET:-HS256}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES:-60}
    ports:
      - "8000:8000"
    depends_on:
      - stock-db-service

  mcp_server:
      build:
        context: ${PWD}/product_mcp_server
        dockerfile: Dockerfile.mcp_server
        # Only way to transmit dynamic values to the Dockerfile
        #   as the environment variables are not exploitable directly there.
        args:
          MCP_SERVER_PORT: ${MCP_SERVER_PORT:-8001}
      container_name: hbntory-mcp-server
      ports:
        # Warning: right side port must match port(s) exposed in DockerFile
        - ${MCP_SERVER_PORT:-8001}:${MCP_SERVER_PORT:-8001}
      environment:
        - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8001}
        # Kept for now in case of, but hardcoded in Python to ensure it listens to all.
        - MCP_SERVER_HOST=0.0.0.0
      # Suggested by AI to better control networks but overkill for us for now,
      #   bad "complexity/benefit" ratio, will be kept as potential security improvement.
      # networks:
      #  - hbntory_net
      restart: unless-stopped

  ai_service:
    build:
      context: ${PWD}/ai_service
      dockerfile: Dockerfile.ai_service
    container_name: hbntory-ai-service
    ports:
      - "${AI_SERVICE_PORT:-8003}:8003"
    environment:
      - AI_SERVICE_PORT=${AI_SERVICE_PORT:-8003}
      # Name of docker service since we are within same network.
      # Here it is not read from .env since it depends on this file's own structure.
      - MCP_SERVER_HOST=product_mcp_server
      # Reusing the variable to ensure we request to the right port.
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8001}
      # Model agnostic configuration (name and if need be API key)
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - LLM_MODEL_API_KEY=${LLM_MODEL_API_KEY}
    depends_on:
      - mcp_server
    restart: unless-stopped


volumes:
  stock_db_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${PWD}/stock_db_data

    # Using an explicit bind mount causes potential problems as the files/folder created for db data
    #   are created "on host filesystem" BUT with inner mariadb user (999).
    # To avoid this we would need to use a custom DockerFile for mariadb container just to set its uid/guid
    # FROM mariadb:latest
    # RUN usermod -u 1000 mysql && groupmod -g 1000 mysql
    # As apaprently this approach does not even provides benefit for data save/recovery strategy let's drop it.

    # Good practice to save is to trigger a dump inside the container but have it redirected to a host file.
    # docker exec hbntory_db mariadb-dump -u root -pH0lb3rt0n holberton_inventory \
    #   > /chemin/vers/nos_backups/backup_$(date +%Y%m%d).sql
