# Docker image with Python preinstalled
FROM python:3.14-slim

# Defining a directory for app inside the container.
WORKDIR /app

# Copying and installing dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copying required files in n steps (for layered cache)
# Everything related to database
COPY database.py db_models.py crud.py ./
# Everything related to backoffice
COPY api_models.py auth.py backoffice_api.py ./
# Related tests files
COPY tests .
# Copy folder holding UI files
COPY static_html ./static_html

# Make logs from Python app appear instantly in docker compose logs
ENV PYTHONUNBUFFERED=1

# Define listening port from environment variable
ENV BACKOFFICE_PORT=8000
EXPOSE ${BACKOFFICE_PORT}

# Setting a command to be runned automatically when container starts
CMD ["sh", "-c", "uvicorn backoffice_api:app --host 0.0.0.0 --port ${BACKOFFICE_PORT}"]
